/*
MIT License

Copyright (c) 2021 Martín Montes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	echoperatorv1alpha1 "github.com/mmontes11/echoperator/pkg/echoperator/v1alpha1"
	versioned "github.com/mmontes11/echoperator/pkg/echoperator/v1alpha1/apis/clientset/versioned"
	internalinterfaces "github.com/mmontes11/echoperator/pkg/echoperator/v1alpha1/apis/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mmontes11/echoperator/pkg/echoperator/v1alpha1/apis/listers/echoperator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EchoInformer provides access to a shared informer and lister for
// Echos.
type EchoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.EchoLister
}

type echoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEchoInformer constructs a new informer for Echo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEchoInformer(
	client versioned.Interface,
	namespace string,
	resyncPeriod time.Duration,
	indexers cache.Indexers,
) cache.SharedIndexInformer {
	return NewFilteredEchoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEchoInformer constructs a new informer for Echo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEchoInformer(
	client versioned.Interface,
	namespace string,
	resyncPeriod time.Duration,
	indexers cache.Indexers,
	tweakListOptions internalinterfaces.TweakListOptionsFunc,
) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MmontesV1alpha1().Echos(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.MmontesV1alpha1().Echos(namespace).Watch(context.TODO(), options)
			},
		},
		&echoperatorv1alpha1.Echo{},
		resyncPeriod,
		indexers,
	)
}

func (f *echoInformer) defaultInformer(
	client versioned.Interface,
	resyncPeriod time.Duration,
) cache.SharedIndexInformer {
	return NewFilteredEchoInformer(
		client,
		f.namespace,
		resyncPeriod,
		cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *echoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&echoperatorv1alpha1.Echo{}, f.defaultInformer)
}

func (f *echoInformer) Lister() v1alpha1.EchoLister {
	return v1alpha1.NewEchoLister(f.Informer().GetIndexer())
}
